name: Manual Reprepro
on:
    workflow_dispatch:
        inputs:
            command:
                description: The command to run, excluding `reprepro -b debian`
                required: true
                type: string
            deploy:
                description: Whether to deploy changes back
                required: false
                type: boolean
                default: false
# Protect reprepro database using concurrency
concurrency: reprepro
jobs:
    reprepro:
        name: Run reprepro
        environment: packages.element.io
        runs-on: ubuntu-latest
        env:
            R2_BUCKET: ${{ vars.R2_BUCKET }}
            R2_DB_BUCKET: ${{ vars.R2_DB_BUCKET }}
            R2_URL: ${{ vars.CF_R2_S3_API }}
        steps:
            - uses: actions/checkout@v3
            - name: Prepare reprepro
              uses: ./.github/actions/setup-reprepro
              with:
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                  gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  gpg-fingerprint: ${{ vars.GPG_FINGERPRINT }}
                  s3-db-bucket: ${{ env.R2_DB_BUCKET }}
                  s3-endpoint-url: ${{ env.R2_URL }}
                  s3-access-key-id: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
                  s3-secret-access-key: ${{ secrets.CF_R2_TOKEN }}

            - name: Run reprepro
              run: |
                  reprepro -b debian ${{ inputs.command }}

            - name: Publish reprepro
              uses: ./.github/actions/push-reprepro
              if: inputs.deploy
              with:
                  s3-bucket: ${{ env.R2_BUCKET }}
                  s3-db-bucket: ${{ env.R2_DB_BUCKET }}
                  s3-endpoint-url: ${{ env.R2_URL }}
                  s3-access-key-id: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
                  s3-secret-access-key: ${{ secrets.CF_R2_TOKEN }}

            - uses: actions/upload-artifact@v4
              if: inputs.deploy == false
              with:
                  name: packages.element.io
                  path: |
                      packages.element.io
                      debian
